apiVersion: apps/v1
kind: Deployment
metadata:
  name: logger-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logger-service
  template:
    metadata:
      labels:
        app: logger-service
    spec:
      containers:
        - name: logger-service
          image: ride-sharing/logger-service
          ports:
            - containerPort: 80
            - containerPort: 5001
            - containerPort: 50001
          env:
            - name: MONGO_URL
              value: "mongodb://admin:password@mongo:27017"
            - name: PORT
              value: "80"
          readinessProbe:
            httpGet:
              path: /ping
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /ping
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: logger-service
spec:
  type: LoadBalancer
  ports:
    - port: 8082
      targetPort: 80
      name: http
    - port: 5001
      targetPort: 5001
      name: rpc
    - port: 50001
      targetPort: 50001
      name: grpc
  selector:
    app: logger-service

